### ISSUE TITLE
Get PDFtoPrinter to ignore embedded Javascript

### ISSUE THREAD

**Issue by n-mueller** [svishnevsky/PDFtoPrinter#13]
Hi,

while using PDFtoPrinter in my windows service, I realized that embedded javascript in pdf-files is executed upon printing. Some of the files I need to print contain js code, which causes the PDFXCview process to not terminate itself after printing and therefore lock the file. 
**Is there a way for the Print()-Method to ignore embedded javascript?**
I work around this problem by killing the process manually by name after every print, which is not a problem because I print the files one at a time. However, this might change in the future so a way to ignore embedded js would be appreciated.

Kind regards

**Comment by svishnevsky** [comment]
Hi @n-mueller,

I released a new version https://www.nuget.org/packages/PDFtoPrinter/1.3.1. Could you please try it and say if the issue still happens?

**Comment by n-mueller** [comment]
Hi @svishnevsky,
I had to manually copy _PDF-XChange Viewer Settings.dat_ to the installation folder, but now it seems to work! Thank you very much.
Can you briefly explain what kind of settings are changed within PDF-XChange Viewer Settings.dat? That would be great.

Kind regards

**Comment by svishnevsky** [comment]
I unchecked "Enable JavaScript Actions" in default settings and added the new version to a package. See below:
![image](https://user-images.githubusercontent.com/2376915/99783351-60a5d180-2b2b-11eb-944d-161412212d88.png)

Actually you can configure [Pdf XChange Viewer](https://www.tracker-software.com/product/pdf-xchange-viewer) as you need, export settings and replace "PDF-XChange Viewer Settings.dat" file.

**Comment by n-mueller** [comment]
Alright, thanks for elaborating!

**Comment by svishnevsky** [comment]
Thanks for contact me with this issue!
