### ISSUE TITLE
where is this exe from ?

### ISSUE THREAD

**Issue by ucandoit1010** [svishnevsky/PDFtoPrinter#16]
Hi ! This is good pdf print tool.

ButI don't understand **PDFtoPrinter.exe** is this 3rd party tool ??
Is it commercial tool ??
Thank you.

**Comment by svishnevsky** [comment]
Hi @ucandoit1010 !

[README.md](https://github.com/svishnevsky/PDFtoPrinter/blob/master/README.md) contains a link to a source of "PDFtoPrinter.exe". It is http://www.columbia.edu/~em36/pdftoprinter.html. See the license text below:

> This system uses the free PDF-Xchange Viewer. You should consult the linked page to determine whether or not you may use that program for your own purposes. The compiled AutoIt script that wraps the PDF software is free for use by anyone, anywhere, for any purposes whatever. Do not waste your valuable time asking me about a license for the AutoIt wrapper; you don't need one.

Regarding the "PDF-Xchange Viewer" license see below:

> PDF-XChange Viewer may be used without limitation for private, commercial, government and all other uses, provided it is not incorporated or distributed for profit/commercial gain with other software or media distribution of any type - without first gaining permission from Tracker Software Products.

**Comment by ucandoit1010** [comment]
I got it !
