### ISSUE TITLE
Is there no black and white color option here, or more printing options? Can you support it?? If you can, this is very, very good

### ISSUE THREAD

**Issue by wangpai1998** [svishnevsky/PDFtoPrinter#17]
Is there no black and white color option here, or more printing options? Can you support it?? If you can, this is very, very good

**Comment by svishnevsky** [comment]
Hi @wangpai1998 

This package is a wrapper over http://www.columbia.edu/~em36/pdftoprinter.html. Unfortunately it doesn't support additional parameters. But you can replace "PDF-XChange Viewer Settings.dat" file with you own with different settings. The "*.dat" file is exported from https://www.tracker-software.com/product/pdf-xchange-viewer.
