### ISSUE TITLE
Do you know if there are some software that can print silently, and the parameters can be set.. If you know, thank you very much!! The CMD command prints something, and so on

### ISSUE THREAD

**Issue by wangpai1998** [svishnevsky/PDFtoPrinter#18]
Do you know if there are some software that can print silently, and the parameters can be set.. If you know, thank you very much!! The CMD command prints something, and so on

**Comment by svishnevsky** [comment]
Sorry, don't know something similar.

**Comment by fdjkdf** [comment]
> 请问有没有什么软件可以静音打印，并且可以设置参数。如果知道的话，非常感谢！！ CMD命令打印一些东西等等

quicker可以。
