### ISSUE TITLE
PDFtoPrinter is updated

### ISSUE THREAD

**Issue by emendelson** [svishnevsky/PDFtoPrinter#2]
Just for your information: I've updated the PDFtoPrinter utility to make it a bit more reliable and to add some new options.

One feature not yet documented: if you add the command-line switch 

focus="Window Title"

the program will return keyboard focus to the window with the title in the parameter. Partial titles will work; you do not need the full title.

**Comment by svishnevsky** [comment]
@emendelson Thanks for letting me know, much appreciated. I updated package with the latest version.
