### ISSUE TITLE
We Can Print Silent

### ISSUE THREAD

**Issue by chuongmep** [svishnevsky/PDFtoPrinter#21]
Dear svishnevsky, 
We can export silent not show dialog pdf with path setting from xml ?

**Comment by svishnevsky** [comment]
Dear @chuongmep ,

Could you please describe what do you need in more details?

**Comment by chuongmep** [comment]
> Dear @chuongmep ,
> 
> Could you please describe what do you need in more details?
I need Print Automatic to folder document a file dont need showdialog question set name file pdf by **Microsoft PDF Printer** .We can do that ?

**Comment by svishnevsky** [comment]
Unfortunately this is out of scope of the package. I can propose change "Microsoft PDF Printer" settings to route all printing to a static file name like the following screenshot:
![image](https://user-images.githubusercontent.com/2376915/106707099-bdc90380-6601-11eb-817d-003aa981631b.png)
Unfortunately this setting is static and it is required to rename a printed file programmatically before the next file is printed to avoid overriding.

**Comment by chuongmep** [comment]
Thanks svishnevsky.
