### ISSUE TITLE
.net 5 support without -windows

### ISSUE THREAD

**Issue by jochenjonc** [svishnevsky/PDFtoPrinter#24]
When upgrading to version 1.4.0 I suddenly got build errors saying I need to the target framework to net5.0-windows. But in my case I reference PdfToPrinter in an assembly that is not an exe. That assembly also has some code that can run on all platforms.

My exe assembly that actually executes PdfToPrinter has net5.0-windows as target framework.

The question is can the net5.0-windows target framework in the code of PdfToPrinter be changed to net5.0?

**Comment by svishnevsky** [comment]
Hi @jochenjonc ! Thanks for contacting me! I'll update the package soon. Please use the previous version until this happened. By the way Could you please tell which TargetFramework  you use in the non exe assembly?

**Comment by svishnevsky** [comment]
Could you please try the latest version https://www.nuget.org/packages/PDFtoPrinter/1.4.1 and tell if it fixes your issue?

**Comment by jochenjonc** [comment]
@svishnevsky the targeframework on the non exe assembly is net5.0.

I just tested v1.4.1 and it works again, thanks for the quick fix.

**Comment by svishnevsky** [comment]
Nice to hear this.
