### ISSUE TITLE
Is this working on windows service

### ISSUE THREAD

**Issue by ucandoit1010** [svishnevsky/PDFtoPrinter#28]
Hi !

I installed PDFtoPrinter on my windows service project.
It is not working ... Printer didn't receive any pdf file.
But working fine with Console app.

Windows form only ?? Or any suggestions ?? thank you.

**Comment by svishnevsky** [comment]
Hi @ucandoit1010 !

I use PDFtoPrinter wit a Windows Service too and it works fine. Could you please confirm the "PDFtoPrinter.exe" is in the Service folder? Do you use a network or local printer? Windows Service might has no permissions to use a local printer.

**Comment by ucandoit1010** [comment]
Thank you.

I print to real printer it works .
If I print to PDF Printer like CutePDF or PDF creator it is not working.

**Comment by svishnevsky** [comment]
Unfortunately Windows Services run in Session 0 that doesn't allow to run any desktop application. See this discussion for more details [https://stackoverflow.com/questions/5307968/how-can-i-run-an-exe-program-from-a-windows-service-using-c](https://stackoverflow.com/questions/5307968/how-can-i-run-an-exe-program-from-a-windows-service-using-c) .

**Comment by ucandoit1010** [comment]
It's ok. 

CutePDF printer is not my online environment.

My service using Epson printer and working fine.
 (set login password for windows account and then control > service > find your service and set login account / pwd ).

After printing PDF file lock by PDF-XChange.
I have no idea how to unlock.
This is my new issue
