### ISSUE TITLE
Network printer not working

### ISSUE THREAD

**Issue by JeffSE97062** [svishnevsky/PDFtoPrinter#30]
I am trying to print to a network printer using the syntax _\\\servername\printername_ and it's not working. No errors from the library and nothing ends up in the print queue. Local printers work fine.

**Comment by svishnevsky** [comment]
@JeffSE97062 

Sorry to hear this. Unfortunately I have no a network printer at the moment to fix it. I'll back to you once I have the same configuration.

**Comment by JeffSE97062** [comment]
Thanks, Sergey. I tried again the next day and found it sometimes printed to those same networked printers and other times it did not. It may be something on my network (which I don't manage) so I wouldn't spend too much time on it.

**Comment by svishnevsky** [comment]
Hi @JeffSE97062 

Just in case, does network printing work better since https://github.com/svishnevsky/PDFtoPrinter/issues/31 is resolved?

**Comment by JeffSE97062** [comment]
@svishnevsky I haven't tested that again as it ultimately started working. We have been having some network printing issues outside of this tool so it wouldn't necessarily be a good test. I'll keep you posted if we start using it for network printing again.
