### ISSUE TITLE
CleanupFilesPrinter not removing files

### ISSUE THREAD

**Issue by JeffSE97062** [svishnevsky/PDFtoPrinter#31]
CleanupFilesPrinter does not delete files after printing. The files are on my local PC and print successfully. I have administrative rights on the box.

**Comment by svishnevsky** [comment]
Hi @JeffSE97062 

Do you run the application with the same permission level as you have? Have you tried to run the app As Administrator?

**Comment by JeffSE97062** [comment]
I did try running as administrator and the file still wasn't removed.

**Comment by svishnevsky** [comment]
Is the application a long running one like service or web server or it exists immediately after sending a file to a printer?

**Comment by JeffSE97062** [comment]
Exits immediately.

**Comment by svishnevsky** [comment]
I see. File cleanup works by timer in background that why it doesn't work in your case. I'll publish an update early next week to support such cases. However files are deleted with a delay, so your application will await the end of the operation.

Thanks,
Sergey
________________________________

**Comment by JeffSE97062** [comment]
Thanks! And thanks for putting this together.

**Comment by svishnevsky** [comment]
Hi @JeffSE97062 

Could you please try the 1.4.2 version and confirm that it solves your issue?

To turn on awaiting of file deletion you need to pass "true" to CleanupFilesPrinter constructor like below:
`new CleanupFilesPrinter(new PDFtoPrinterPrinter(), true);`

**Comment by JeffSE97062** [comment]
Hi @svishnevsky, same issue with the 1.4.2. The file is not removed.

**Comment by svishnevsky** [comment]
Do you use a similar approach like below?
`var wrapper = new CleanupFilesPrinter(new PDFtoPrinterPrinter(), true);
 await wrapper.Print(new PrintingOptions("Microsoft Print to PDF", "somefile.pdf"));'

**Comment by JeffSE97062** [comment]
Yes.
`
    class Program
    {
        static void Main(string[] args)
        {
            print();
        }

        static async void print()
        {
            // Delete after printing. Doesn't seem to work.
            var wrapper = new CleanupFilesPrinter(new PDFtoPrinterPrinter(), true);

            await wrapper
                .Print(new PrintingOptions(
                    Properties.Settings.Default.Printer,
                    Properties.Settings.Default.FileToPrint)
                    );

        }
    }`

**Comment by svishnevsky** [comment]
Thanks for sharing the code. You call the "print" method with no await, so your application exists before a Task is completed. Could you please try something like:
`
static sync Task Main(string[] args)
{
  await print()
}
`
or
`
static void Main(string[] args)
{
  print(),GetAwaiter().GetResult();
}
`

**Comment by JeffSE97062** [comment]
That worked. Thanks.
