### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by ThomasBernardPageUp** [svishnevsky/PDFtoPrinter#34]
Hi, I tried this package in a console project, everything works great but now I use it in a WPF project and I get this error :

![image](https://user-images.githubusercontent.com/90254070/151780928-3ec89c04-27da-4fa0-bb01-5a110300bcf8.png)

![image](https://user-images.githubusercontent.com/90254070/151780955-7c87378b-242f-45e2-96cf-289d1fa6c3ba.png)
This code work in a console project so why not in WPF ? (The file exist in the default path)

**Comment by svishnevsky** [comment]
Hi @ThomasBernardPageUp 

Did you solve your issue?

**Comment by ThomasBernardPageUp** [comment]
Hi @svishnevsky 
No I think it just did not work in WPF application

**Comment by svishnevsky** [comment]
It should work. Could you please provide a little bit more details?

1) Which .Net version you use in your WPF application?
2) Did you install PDFtoPrinter NuGet package directly to the WPF project or to one of referenced projects?

**Comment by ThomasBernardPageUp** [comment]
The WPF application is in .NET Core 3.1, but m method to print is in a class Library in .Net Core 3.1. I install the package only in Class library

**Comment by svishnevsky** [comment]
Thanks for the details. Unfortunately there are an open issue https://github.com/svishnevsky/PDFtoPrinter/issues/29. You need to install the package to the WPF project directly at the moment.

**Comment by ThomasBernardPageUp** [comment]
Ok thanks
