### ISSUE TITLE
Resize PDF

### ISSUE THREAD

**Issue by aselby** [svishnevsky/PDFtoPrinter#35]
Add a way to resize each page in the PDF to a standard page size.

**Comment by svishnevsky** [comment]
Hi @aselby 

Sorry for the long response.

Could you please check version 1.4.3 https://www.nuget.org/packages/PDFtoPrinter/1.4.3 ? Does it fix your issue?

**Comment by svishnevsky** [comment]
Closing issue as here are no new activity.

**Comment by marcocecchi** [comment]
Hi Sergey, 
I have v1.5.2 but my printer ask me to change paper format because some PDFs have incorrect page dimensions (210,6 x 295,4) so I'd like to know if there is a parameter that could shrink or fit the page to a standard A4 format.
Thanks in advance,
Marco
