### ISSUE TITLE
Multi Printer

### ISSUE THREAD

**Issue by osmanreset** [svishnevsky/PDFtoPrinter#39]
Hello
I want to throw files to several printers at the same time with "BackgroundWorker" in C#.
But I am getting the error in the picture.
I request your support

![hatapdf özel](https://user-images.githubusercontent.com/77679920/172848005-f595def5-b224-4186-b336-384dc03f1ec1.png)

**Comment by svishnevsky** [comment]
Hello @osmanreset !
Thanks for your request. I've updated the package. Could you please try version 1.4.4 and check if it works fine for you?

**Comment by osmanreset** [comment]
Thank you.
