### ISSUE TITLE
select printer tray

### ISSUE THREAD

**Issue by wtang2006** [svishnevsky/PDFtoPrinter#42]
is there a way to select a tray in a printer?

**Comment by svishnevsky** [comment]
Hi @wtang2006 

The only way to change a tray is to update "PDF-XChange Viewer Settings.dat" with you own settings. See more information here http://www.columbia.edu/~em36/pdftoprinter.html:

> By default, this system uses these printing options as set in PDF-XChange Viewer: Scaling is set to None; Auto-rotate Sheets; Auto-centre pages in sheets; and Choose **paper source** by PDF-page size. If you want to change any of these, or choose any other options, download and install PDF-XChange Viewer; open a PDF file, go to the Print menu, set your desired options (and, just to be certain, print the file). Then go to the Edit menu and choose Export All Settings to Data File... Accept the suggested filename, "PDF-XChange Viewer Settings.dat", and save the file to a convenient location. Move or copy the file to the same folder with PDFtoPrinter.exe. When you next run PDFtoPrinter.exe it will use the settings saved in that file.
