### ISSUE TITLE
Suggestion: Print PDF from a stream

### ISSUE THREAD

**Issue by MajidAbuRmelah** [svishnevsky/PDFtoPrinter#43]
Can there be an option to print from a stream?

I would like to download a pdf file and store it in a variable as a stream and print it.

Thanks in advance.

**Comment by svishnevsky** [comment]
Hi @MajidAbuRmelah 
Thanks for you suggestion. It is done in version 1.5.0. See sources here https://github.com/svishnevsky/PDFtoPrinter/blob/master/PDFtoPrinter/IPrinterStreamExtentions.cs.
