### ISSUE TITLE
use `<PublishSingleFile>true</PublishSingleFile>` not found directory name.

### ISSUE THREAD

**Issue by juner** [svishnevsky/PDFtoPrinter#44]
It works fine when I debug it, but when I publish it and run it, it doesn't work.

As far as I can see the source, here I am getting DirectoryName from Location
https://github.com/svishnevsky/PDFtoPrinter/blob/20a99d757a9be1ef8b1ddcd3c58ebeec1785722d/PDFtoPrinter/PDFtoPrinterPrinter.cs#L90-L93

Shouldn't it fall back to AppContext.BaseDirectory if the Location return value is an empty string?

see https://github.com/dotnet/corert/issues/5467

sample project: https://github.com/juner/PdfToPrinterNotWorkSample_20230214

**Comment by svishnevsky** [comment]
Hi @juner 
Thanks for reporting the issue. Could you please try version 1.5.0 and let me know if it helped?

**Comment by juner** [comment]
@svishnevsky 
it worked fine
Thank you very much! !
