### ISSUE TITLE
Support for .Net Standard 2.0

### ISSUE THREAD

**Issue by jochenjonc** [svishnevsky/PDFtoPrinter#5]
I have a .Net Core project and would like to use this library, but I've seen only full framework is supported.

The reason is probably the reference to System.Printing, but I've seen this is only used in the CleanupFilesPrinter.

Are you open for a .net standard compatible version, without support for CleanupFilesPrinter?

**Comment by svishnevsky** [comment]
Hi @jochenjonc 
Thanks for your question. I can add .net standard support but this package will work on windows systems only because it uses an exe file for printing purposes.

**Comment by jochenjonc** [comment]
I know it would only work on windows, but it is exactly the combination of .net core 2.2 app on a windows machine that needs te print a pdf that is not working.
As far as I know, printing works again since .net core 3.0.

**Comment by svishnevsky** [comment]
@jochenjonc The new version is available https://www.nuget.org/packages/PDFtoPrinter/1.2.0. Could you please try to use it and say if everything fine for you?

**Comment by jochenjonc** [comment]
@svishnevsky I got it working with the latest version of the library. Thx.

I had a small issue that my application could not find the PDFtoPrinter.exe. The reason is that I reference your library in an assembly and that assembly is referenced in my exe.
In the bin folder of my assembly, I see the PDFtoPrinter.exe, but it was not copied to the bin of my exe when compiling.
I was able to solve it by also referencing your library in my exe.

**Comment by svishnevsky** [comment]
Thanks @jochenjonc  for your feedback, much appreciated!  
Not sure if this possible to copy "PDFtoPrinter.exe" to the Application output directory without direct referencing "PDFtoPrinter" package but I will investigate this question.

Feel free to come back with any issues or improvements.
