### ISSUE TITLE
When doing a publish the PDFtoPrinter.exe is not copied

### ISSUE THREAD

**Issue by jochenjonc** [svishnevsky/PDFtoPrinter#8]
Hi,

I had an issue when doing a publish (with .Net Core 3.1.5) that the PDFtoPrinter.exe was not present in the published folder. I solved it by adding the following to my csproj.

```xml
<Target Name="CopyPDFtoPrinterExe" AfterTargets="Publish">
    <Copy SourceFiles="$(OutDir)\PDFtoPrinter.exe" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
</Target>
```

But maybe it can also be added to the [PDFtoPrinter.targets](https://github.com/svishnevsky/PDFtoPrinter/blob/master/PDFtoPrinter/build/PDFtoPrinter.targets).

I'm not sure if it would help, but I hope so.

Kind regards,

Jochen

**Comment by svishnevsky** [comment]
Thanks for the code example, much appreciated. The nuget package is updated to version 1.2.1 https://www.nuget.org/packages/PDFtoPrinter/1.2.1.

**Comment by jochenjonc** [comment]
Hey Sergey,

I just tested it and it works like a charm.

Regards,

Jochen

**Comment by wurstl666** [comment]
Hi,

i have same problem again. No exe after publish. I use .Net Framework 4.7 and the PDFtoPrinter Version V1.3.1.

Any idea what i do wrong?

Thank you

**Comment by svishnevsky** [comment]
Hi @wurstl666 

Sorry for the late response. Could you please try the newest version 1.3.2 and let me know if this help?

**Comment by wurstl666** [comment]
Looks good! Thank you very much!
