### ISSUE TITLE
PDFtoPrinter (June 2020)

### ISSUE THREAD

**Issue by jochenjonc** [svishnevsky/PDFtoPrinter#9]
Hi,

There seems to be a newer version of PDFtoPrinter (June 2020), see http://www.columbia.edu/~em36/pdftoprinter.html.

Regards,

Jochen

**Comment by emendelson** [comment]
And I've updated it again to fix some problems with the latest Windows 10 update, and to add to the command-line options.

**Comment by svishnevsky** [comment]
Thanks for pointing me to this. The nuget package is updated to version 1.2.1 https://www.nuget.org/packages/PDFtoPrinter/1.2.1.
